### ISSUE TITLE
GSEApy Exception: Error analyzing gene list

### ISSUE THREAD

**Issue by Wendy-k2** [zqfang/GSEApy#117]
I met this problem when I implement gseapy.enrichr function to a single cell RNAseq database. I have conducted classfication and cell type annotation. Does this exception mean that the gene name in my database can't be found in the gene library? Do you have any suggestions on how to cope with this problem?
![image](https://user-images.githubusercontent.com/81276160/112247647-0cbb0e80-8c2b-11eb-8b5d-d59766a16779.png)
![image](https://user-images.githubusercontent.com/81276160/112247849-5efc2f80-8c2b-11eb-8f7d-5daeb3eb29b8.png)

**Comment by ealsop** [comment]
Hello. I am also encountering this error when running. Since this line is as given in the manual, please advise. Thanks.

gseapy.enrichr(gene_list=glist, description='pathway', gene_sets='KEGG_2016', outdir='test')

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-21-fa69a6e1a12a> in <module>
----> 1 gseapy.enrichr(gene_list=glist, description='pathway', gene_sets='KEGG_2016', outdir='test')

~/anaconda3/envs/scanpy/lib/python3.8/site-packages/gseapy/enrichr.py in enrichr(gene_list, gene_sets, organism, description, outdir, background, cutoff, format, figsize, top_term, no_plot, verbose)
    500     # set organism
    501     enr.set_organism()
--> 502     enr.run()
    503 
    504     return enr

~/anaconda3/envs/scanpy/lib/python3.8/site-packages/gseapy/enrichr.py in run(self)
    403                 self._logger.debug("Start Enrichr using library: %s" % (self._gs))
    404                 self._logger.info('Analysis name: %s, Enrichr Library: %s' % (self.descriptions, self._gs))
--> 405                 shortID, res = self.get_results(genes_list)
    406                 # Remember gene set library used
    407             res.insert(0, "Gene_set", self._gs)

~/anaconda3/envs/scanpy/lib/python3.8/site-packages/gseapy/enrichr.py in get_results(self, gene_list)
    178         """Enrichr API"""
    179         ADDLIST_URL = '%s/%s/addList'%(self.ENRICHR_URL,  self._organism)
--> 180         job_id = self.send_genes(gene_list, ADDLIST_URL)
    181         user_list_id = job_id['userListId']
    182 

~/anaconda3/envs/scanpy/lib/python3.8/site-packages/gseapy/enrichr.py in send_genes(self, gene_list, url)
    158         response = requests.post(url, files=payload)
    159         if not response.ok:
--> 160             raise Exception('Error analyzing gene list')
    161         sleep(1)
    162         job_id = json.loads(response.text)

Exception: Error analyzing gene list

**Comment by zqfang** [comment]
Sorry for replying late. This error means Enrichr server could not be reached sometimes. If the error gone now?

**Comment by Wendy-k2** [comment]
I tried again and this error is gone, but I got the error 'Adjusted P-value' as issue #116 .Do you have any suggestions for that? Thanks!

**Comment by zqfang** [comment]
@Wendy-k2 , you could set `no_plot= True` to skip generating pdf files

**Comment by Wendy-k2** [comment]
Thanks. Does it mean that p-value couldn't be generated as intended? When I run code "gseapy.barplot(enr_res.res2d,title='GO_Biological_Process_2018')" , I still get the same error 'Adjusted P-value'. 
Besides, the result came out is weird and doesn't work as the tutorial. Screenshot attached. Is there anything wrong with the implementation?
![image](https://user-images.githubusercontent.com/81276160/113711036-7539cf00-96b2-11eb-940b-a731b0d6cb56.png)

**Comment by zqfang** [comment]
It looks like Enrichr server changed output format.

**Comment by zqfang** [comment]
I don't understand. I couldn't reproduce the issues. Your `glist` isn't empty, right?

**Comment by LeslieDsr** [comment]
Hello, I’m bringing this up again because I’ve been facing a lot of server errors over the past two days (Exception: Error sending gene list, try again later), more often than usual. I’m not sure if there’s maintenance on the Enrichr server or if it’s coming from pyGSEA API (e.g. new URL connexion update) ? :)

**Comment by bradwbradw** [comment]
It seems to work 1 out of every 20 attempts

**Comment by KalinNonchev** [comment]
Same here...

**Comment by zqfang** [comment]
I did not see the server url has been changed. may be you use the gmt file input for now (without connecting to enrichr server)

**Comment by zqfang** [comment]
I just tried. I did not have any issue connecting to the Enrichr Service.

**Comment by KalinNonchev** [comment]
It is unstable these days... Anyway, downloading the GMT files from https://maayanlab.cloud/Enrichr/#libraries solved it.

**Comment by KalinNonchev** [comment]
Thanks for the quick response!
