### ISSUE TITLE
Can I use GSEApy for gene enrichment analysis of non-model organisms?

### ISSUE THREAD

**Issue by Skychou-source** [zqfang/GSEApy#196]
Respected Professor：
   I am currently developing a parameter-free RNA-seq analysis pipeline. For the functional annotation part, I would like to use your GSEApy.But I am currently facing some problems.
  In the previous steps, I obtained a table that contains various annotation information (background information) for all distinguishable transcripts of the current analysis object. The format of this form is as follows:

**- Gene Names               Gene Ontology (GO)
- TDH2 GPD2 YJR009C J1433  cytoplasm [GO:0005737]; cytosol [GO:0005829];......
- TDH3 GPD3 YGR192C G7576  fungal-type cell wall [GO:0009277]; lipid droplet [GO:0005811];......**

   Additionally, I also know which Gene Names are differentially expressed genes. Upregulated or downregulated genes, as well as fold-change and padj.
   But how do I use GSEApy for further analysis? I want to create bar charts similar to GO enrichment analysis, etc. My main goal is gene enrichment analysis and visualization. However, it seems that there are no tools currently available that can satisfy the enrichment analysis of non-reference species.
  Sorry to bother you. Looking forward to your reply. Thank you again!

**Comment by Skychou-source** [comment]
Regarding the format of the master list, here is some additional information to avoid any misunderstandings:
It has two columns, one column is the gene name (which may contain multiple genes), and the second column is the GO entry, which includes ID and description information (there are also many entries).

Gene Names               Gene Ontology (GO)
TDH2 GPD2 YJR009C J1433  cytoplasm [GO:0005737]; cytosol [GO:0005829];......
TDH3 GPD3 YGR192C G7576  fungal-type cell wall [GO:0009277]; lipid droplet [GO:0005811];......

**Comment by zqfang** [comment]
I'm not a professor, sorry.

I don't understand your question. What do you mean by "no tools currently available that can satisfy the enrichment analysis of non-reference species" ?

what species you'er working on with? 

You can always map your gene names to the available species to do the analysis, or vice verse.

**Comment by Skychou-source** [comment]
I am very grateful for your response and apologize for any confusion I may have caused. The meaning of 'no tools currently available that can satisfy the enrichment analysis of non-reference species' is that I have not found any tools that can perform gene enrichment analysis on non-reference species. Regarding 'what species you're working on with?', since I am developing a workflow tool, I do not know what species it is yet. Is it necessary to select a species in order to run your tool? Thank you again!  :)

**Comment by armadillocommander** [comment]
I didn’t get it, what’s the difference between the non-canonical species and reference species? Why Java version GSEA and gseapy cannot work on other species?I used both to perform enrichment analysis for species like Komagataella phaffii with no problem. May be you should have a try first.Sent from my iPhoneOn Apr 7, 2023, at 6:41 PM, 周天瑞 ***@***.***> wrote:﻿
I am very grateful for your response and apologize for any confusion I may have caused. The meaning of 'no tools currently available that can satisfy the enrichment analysis of non-reference species' is that I have not found any tools that can perform gene enrichment analysis on non-reference species. Regarding 'what species you're working on with?', since I am developing a workflow tool, I do not know what species it is yet. Is it necessary to select a species in order to run your tool? Thank you again!  :)

**Comment by Skychou-source** [comment]
I'll give you an example. If I want to study a non-model organism, such as a certain type of fungus, how can I use your tool?

**Comment by zqfang** [comment]
You should try gseapy or GSEA java first, then ask how

Both of them required a GMT file for enrichment analysis. For commonly used species, there're a lot of databases that have curated gene sets (pathways). For your example, you'll need to create the GMT file yourself.

**Comment by Skychou-source** [comment]
I understand what you mean now, thank you for patiently replying!：）
