### ISSUE TITLE
Exited with code=null when apply gseapy for a big .gmt file

### ISSUE THREAD

**Issue by Sunmile** [zqfang/GSEApy#233]
Hi Fang,
Thanks for the useful tools developing! 
I came across an error when I used the GSEApy to do the ssgsea analysis on a big .gmt file.
The following is the .gmt file I used which contains about 10k gene sets. (All GO gene sets from gsea-msigdb website)

https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2023.2.Hs/c5.go.v2023.2.Hs.symbols.gmt

Here is my code:
```
gs_res = gp.ssgsea(
    data=df_gsea,
    gene_sets=gene_set,
    outdir="./../result/Subtype_iso/ssGSEA",
    sample_norm_method="rank",
    correl_norm_type="zscore",
    permutation_num=1000,
)
```
The df_gsea is my input gene expression matrix whose shape is (10000,100).
But It will be exited with no output after about 40min running.
```
[Done] exited with code=null in 2723.898 seconds
```
Another information:
It works on a small .gmt file (about 1k gene sets) with the same input and code.

I would appreciate it if you could give any help or suggestions for this problem.

Many thanks,
Sunmile

**Comment by zqfang** [comment]
can you print out the version of gseapy you've used? 

my guess is that your program exited because of the out-of-memory issue (10k genes with 1000 permutations).

NOTE: when you use ssgsea, permutation_num should set to 0. the program will finished in seconds.

if you really wanna try permutation_num > 0, try split your large gmt file into smaller ones (just like what you did), then concat your results will be fine.

**Comment by Sunmile** [comment]
Thank you for your prompt response.
The version of gseapy is 1.0.6.
I agree with your speculation. I tried setting the permutation time to 0, and indeed, the results were calculated in about 20 seconds. Ignoring the pval and fdr, I found the NES are different when I set the permutation_num to 0 and 1000.  However, the relative rank is similar in all samples. Therefore, I think the permutation_num=0 results are enough for me.
Thanks a lot.
