### ISSUE TITLE
expected enrichment score of -0.5, got -0.496 instead

### ISSUE THREAD

**Issue by ghost** [zqfang/GSEApy#47]
Hello

I'm doing a trivial example where I created a gene set of the 49 most up-regulated genes of the in my dataset and then running ssgsea.  In this trivial example I expect to get an enrichment score of -0.5, but instead I get -0.496.

The command I used:
`ss2 = gseapy.ssgsea(g.data_df.iloc[:, :1], gene_sets=geneset_output_file, verbose=True, format="png", outdir="temp2")`

I can provide the data and gene set (`geneset_output_file`) if you would like.  Here is the output file `temp2/gseapy.ssgsea.gene_sets.report.csv`, the relevant line is `example_up`:
```
# normalize enrichment scores by random permutation procddure
# Same method to the orignial GSEA method, and it's not proper to use these values in your publication
Term	es	nes	pval	fdr	gene_set_size	matched_size	genes
example_dn	0.500053595619	8.26711866264	0.0	0.0	49	49	8869,9053,9170,80204,4775,7048,976,7376,22905,6839,79921,28969,5873,93487,6988,9653,3508,1870,55011,55746,64746,8270,2767,57178,23443,54957,211,2769,7043,9143,4998,10954,6944,7099,7165,51001,23161,8837,55825,5867,10732,808,93594,891,8985,4482,10610,8446,637
example_up	-0.496476958504	-22.8445330718	0.0	0.0	49	49	3383,7158,256364,23097,2146,23139,355,30849,10285,56654,5641,23386,8518,10276,178,147179,8573,993,9448,63874,6195,51335,25966,1445,83743,26128,392,890,8895,23,9375,56889,10450,26511,57761,51024,10245,23014,10493,1019,9928,1802,11188,9093,1633,51282,4144,51160,9709
```
 
You can see the `es` for `example_up` is `-0.496476958504` instead of the expected -0.5

Thank you in advance, any ideas / thoughts greatly appreciated.

**Comment by zqfang** [comment]
How did you normalize your data?  
The implement of GSEApy's ssgsea is slightly different from the R ssGSEAProjection, whose source code is more complicated. This might be the reason.

**Comment by dllahr-foghorntx** [comment]
If you mean the input data (i.e. `g.data_df.iloc[:, :1]) I didn't do anything to normalize it.  I don't think this should matter though.  FWIW the values are "robust z-scores" from Connectivity Map (CMap) L1000 public data.

**Comment by zqfang** [comment]
Could you send me your input files?

**Comment by dllahr-foghorntx** [comment]
Sure thank you for looking into this.  This is slightly different than the original (I've switched the dn and up) but otherwise identical.  Here is a gct containing the data I used:
[example_input.gct.gz](https://github.com/zqfang/GSEApy/files/2228220/example_input.gct.gz)

Here is the gmt file for my genesets:
[example_genesets.gmt.gz](https://github.com/zqfang/GSEApy/files/2228224/example_genesets.gmt.gz)

Here are the outputs:
[gseapy.samples.normalized.es.txt](https://github.com/zqfang/GSEApy/files/2228226/gseapy.samples.normalized.es.txt)
[gseapy.samples.raw.es.txt](https://github.com/zqfang/GSEApy/files/2228227/gseapy.samples.raw.es.txt)
![example_dn ssgsea](https://user-images.githubusercontent.com/36932252/43206847-9f5afe5c-8ff4-11e8-829b-e4e2f6e42ddc.png)
![example_up ssgsea](https://user-images.githubusercontent.com/36932252/43206848-9f64ebce-8ff4-11e8-88dd-1c31ce858bf1.png)

**Comment by dllahr-foghorntx** [comment]
Hi

I've run into what I think is a more serious consequence of the above asymmetry in the calculation.  Instead of creating genesets that are the 50 most upregulated or 50 most downregulated genes, I created a geneset of 50 genes was pulled randomly from the ~500 upregulated genes, and another geneset of 50 genes pulled randomly from the ~500 downregulated genes.  I used ssgsea (single sample GSEA) to calculate ES for these.  I then inverted the dataset, calculated ranks, and re-ran using the same genesets.  I believe the ES values should just be inverted / negative of those in the first calculation but they were not.  I've attached images from output to illustrate this and a jupyter notebook that I used.

First, for the downregulated gene sets, here are the plots of the gene positions.  I flipped on of the images horizontally so they can be compared directly - you can see they line up:
![comparison of moderate_50dn plots geneset element positions](https://user-images.githubusercontent.com/36932252/43670615-ad3c3860-975b-11e8-86e6-c6116cff468c.png)

Here are the corresponding mountain plots - one has been flipped horizontally and then vertically to all direct comparison:
![comparison of moderate_50dn mountain plots](https://user-images.githubusercontent.com/36932252/43670631-f76d72be-975b-11e8-930c-a9b167fb440e.png)

It seems to me that the pattern matches, however in the lower trace the individual step produces a larger y-axis change, causing a return to zero more quickly than in the upper trace, leading to an ES with a lower absolute value.

Finally just want to mention that I initially noticed the severity of the problem when I ran a large calculation to calculate enrichment scores between publicly available CMap / L1000 data (genesets calculated from this dataset, then ssGSEA calculated between these genesets and the same differential gene expression signatures).  The distribution of values I calculate is centered at somewhat positive values - for both up and down regulated genesets, and both are also skewed.  Here are some  example histograms:

![image](https://user-images.githubusercontent.com/36932252/43670694-0b2e75e0-975d-11e8-9b62-190a4f27593e.png)
^^ upregulated genesets compare to signatures (A549 cell line)

![image](https://user-images.githubusercontent.com/36932252/43670707-31a59582-975d-11e8-89b9-b78103266f64.png)
^^ downregulated genesets compared to signatures (A549 cell line)

![image](https://user-images.githubusercontent.com/36932252/43670714-43162548-975d-11e8-8b92-a08296f1be3b.png)
^^ both of the above histograms on the same plot

**Comment by dllahr-foghorntx** [comment]
Quick update:  I discovered that if I run with weighted_score_type = 0.0 I get the symmetric behavior I expect.  But I'm not sure what that means scientifically.
